.TH MAP 1
.SH NAME
map \- or, how to find out where here is
.SH SYNOPSIS
.B map
[\fILEVELS\fR]
[\fIPATH\fR]
.SH DESCRIPTION
So, you are lost and confused?  Don't worry, the \fBmap\fR spell will help you get your bearings.
By default, the bare spell will show the town of Greymore and three "sub-places". However, if you provide a numeric argument, it will show that many "sub-places"
.PP
If you provide a second argument, the map will be displayed relative to that directory.
.SH UNIX
This command is an alias for the \fIexa\fR tool, which is an alternative to \fIls\fR (it is \fBnot\fR builtin) in tree mode and was included for this game.

There is another utility called \fItree\fR that performs the same function (displaying a recursive listing of directories in a tree-like style, but few unix distros include it.
The closest builtin utility would be \fIls\fR in recursive (-R) mode.
